import { PrismaClient, RecipeMealType, Difficulty } from '@prisma/client';

export async function seedRecipes(prisma: PrismaClient) {
    const recipesData = [
        {
            title: 'Blueberry Oat Porridge',
            imageUrl: 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=500&q=80',
            recipeMealType: RecipeMealType.BREAKFAST,
            minAgeMonths: 6,
            maxAgeMonths: 24,
            prepTimeMin: 5,
            cookTimeMin: 10,
            difficulty: Difficulty.EASY,
            servings: '2-3',
            nutritionalFocus: ['Growth & Energy', 'Finger Food Friendly', 'Balanced'],
            safetyNotes: 'Cut into small pieces for toddlers.',
            ingredients: [
                { name: 'Organic Banana', amount: '1 unit', substitute: 'apple puree', isOptional: false },
                { name: 'Egg', amount: '1 unit', substitute: 'flax egg', isOptional: false },
                { name: 'Oats', amount: '1 unit', substitute: 'oat flour', isOptional: false },
                { name: 'Olive oil', amount: '1 unit', substitute: 'oat flour', isOptional: true },
            ],
            steps: [
                { stepNumber: 1, description: 'Mash banana in a bowl until completely smooth with no lumps.' },
                { stepNumber: 2, description: 'Add egg and oats and mix until a thick batter forms.' },
                { stepNumber: 3, description: 'Add a small amount of oil and spread evenly.' },
                { stepNumber: 4, description: 'Spoon batter into small rounds.' },
                { stepNumber: 5, description: 'Cook for 2-3 minutes until bubbles appear and edges set.' },
                { stepNumber: 6, description: 'Flip and cook for 2 more minutes until golden and firm.' },
            ],
        },
        {
            title: 'Avocado Toast with Egg',
            imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=500&q=80',
            recipeMealType: RecipeMealType.BREAKFAST,
            minAgeMonths: 12,
            maxAgeMonths: 36,
            prepTimeMin: 5,
            cookTimeMin: 5,
            difficulty: Difficulty.EASY,
            servings: '1',
            nutritionalFocus: ['Brain Development', 'High Protein'],
            safetyNotes: 'Ensure egg is fully cooked to avoid salmonella risk.',
            ingredients: [
                { name: 'Whole wheat bread', amount: '1 slice', substitute: 'gluten-free bread', isOptional: false },
                { name: 'Avocado', amount: '1/2 unit', substitute: 'hummus', isOptional: false },
                { name: 'Egg', amount: '1 unit', substitute: null, isOptional: false },
                { name: 'Pinch of salt', amount: '1 pinch', substitute: null, isOptional: true },
            ],
            steps: [
                { stepNumber: 1, description: 'Toast the bread until golden brown.' },
                { stepNumber: 2, description: 'Mash the avocado and spread it over the toast.' },
                { stepNumber: 3, description: 'Cook the egg (scrambled or fried) and place on top.' },
            ],
        },
        {
            title: 'Sweet Potato Fries',
            imageUrl: 'https://images.unsplash.com/photo-1596693892790-95167098e9b6?w=500&q=80',
            recipeMealType: RecipeMealType.SNACK,
            minAgeMonths: 9,
            maxAgeMonths: 48,
            prepTimeMin: 10,
            cookTimeMin: 20,
            difficulty: Difficulty.EASY,
            servings: '2',
            nutritionalFocus: ['Vitamins', 'Finger Food'],
            safetyNotes: 'Serve at room temperature to avoid burns.',
            ingredients: [
                { name: 'Sweet potato', amount: '1 large', substitute: 'butternut squash', isOptional: false },
                { name: 'Olive oil', amount: '1 tbsp', substitute: 'coconut oil', isOptional: false },
                { name: 'Paprika', amount: '1/2 tsp', substitute: null, isOptional: true },
            ],
            steps: [
                { stepNumber: 1, description: 'Preheat oven to 400°F (200°C).' },
                { stepNumber: 2, description: 'Peel and cut sweet potato into stick shapes.' },
                { stepNumber: 3, description: 'Toss with oil and paprika.' },
                { stepNumber: 4, description: 'Bake for 20 minutes, flipping halfway.' },
            ],
        },
        {
            title: 'Mini Chicken Meatballs',
            imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=500&q=80',
            recipeMealType: RecipeMealType.LUNCH,
            minAgeMonths: 10,
            maxAgeMonths: 60,
            prepTimeMin: 15,
            cookTimeMin: 15,
            difficulty: Difficulty.MEDIUM,
            servings: '4',
            nutritionalFocus: ['High Protein', 'Iron'],
            safetyNotes: 'Cut into halves or quarters for younger toddlers.',
            ingredients: [
                { name: 'Ground chicken', amount: '1 lb', substitute: 'ground turkey', isOptional: false },
                { name: 'Breadcrumbs', amount: '1/4 cup', substitute: 'oat flour', isOptional: false },
                { name: 'Grated carrot', amount: '1/4 cup', substitute: 'zucchini', isOptional: false },
            ],
            steps: [
                { stepNumber: 1, description: 'Mix all ingredients in a bowl.' },
                { stepNumber: 2, description: 'Form into small bite-sized balls.' },
                { stepNumber: 3, description: 'Pan-fry or bake until fully cooked inside.' },
            ],
        },
        {
            title: 'Creamy Spinach Pasta',
            imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&q=80',
            recipeMealType: RecipeMealType.DINNER,
            minAgeMonths: 12,
            maxAgeMonths: 72,
            prepTimeMin: 5,
            cookTimeMin: 15,
            difficulty: Difficulty.EASY,
            servings: '3',
            nutritionalFocus: ['Iron', 'Calcium', 'Energy'],
            safetyNotes: 'Ensure pasta is cooked very soft for early eaters.',
            ingredients: [
                { name: 'Pasta (fusilli)', amount: '1 cup', substitute: 'macaroni', isOptional: false },
                { name: 'Spinach', amount: '1 cup', substitute: 'kale', isOptional: false },
                { name: 'Cream cheese', amount: '2 tbsp', substitute: 'cashew cream', isOptional: false },
            ],
            steps: [
                { stepNumber: 1, description: 'Boil pasta until tender, then drain.' },
                { stepNumber: 2, description: 'Blend spinach and cream cheese into a smooth sauce.' },
                { stepNumber: 3, description: 'Toss warm pasta with the sauce.' },
            ],
        },
        {
            title: 'Banana Pancake Bites',
            imageUrl: 'https://images.unsplash.com/photo-1598214886806-c87b84b7078b?w=500&q=80',
            recipeMealType: RecipeMealType.SNACK,
            minAgeMonths: 8,
            maxAgeMonths: 48,
            prepTimeMin: 5,
            cookTimeMin: 10,
            difficulty: Difficulty.EASY,
            servings: '2',
            nutritionalFocus: ['Quick Energy', 'Potassium'],
            safetyNotes: 'Cool before serving.',
            ingredients: [
                { name: 'Banana', amount: '1', substitute: 'apple sauce', isOptional: false },
                { name: 'Egg', amount: '1', substitute: 'flax egg', isOptional: false },
                { name: 'Cinnamon', amount: '1 pinch', substitute: null, isOptional: true },
            ],
            steps: [
                { stepNumber: 1, description: 'Mash banana and whisk with the egg.' },
                { stepNumber: 2, description: 'Pour small circles of batter onto a greased pan.' },
                { stepNumber: 3, description: 'Cook until golden on both sides.' },
            ],
        },
        {
            title: 'Mild Vegetable Curry',
            imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=500&q=80',
            recipeMealType: RecipeMealType.DINNER,
            minAgeMonths: 18,
            maxAgeMonths: 72,
            prepTimeMin: 15,
            cookTimeMin: 25,
            difficulty: Difficulty.MEDIUM,
            servings: '4',
            nutritionalFocus: ['Immunity', 'Fiber', 'Vitamins'],
            safetyNotes: 'Check temperature before serving. Cut veggies small.',
            ingredients: [
                { name: 'Mixed veggies (carrots, potatoes)', amount: '2 cups', substitute: 'sweet potato, peas', isOptional: false },
                { name: 'Coconut milk', amount: '1/2 cup', substitute: 'yogurt', isOptional: false },
                { name: 'Mild curry powder', amount: '1/2 tsp', substitute: 'turmeric & cumin', isOptional: false },
            ],
            steps: [
                { stepNumber: 1, description: 'Sauté veggies until slightly soft.' },
                { stepNumber: 2, description: 'Add spices and coconut milk.' },
                { stepNumber: 3, description: 'Simmer until vegetables are completely tender.' },
            ],
        },
        {
            title: 'Apple & Carrot Muffins',
            imageUrl: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=500&q=80',
            recipeMealType: RecipeMealType.SNACK,
            minAgeMonths: 12,
            maxAgeMonths: 60,
            prepTimeMin: 15,
            cookTimeMin: 20,
            difficulty: Difficulty.MEDIUM,
            servings: '6',
            nutritionalFocus: ['Fiber', 'No Added Sugar'],
            safetyNotes: 'Break into pieces before giving to young toddlers.',
            ingredients: [
                { name: 'Grated apple', amount: '1/2 cup', substitute: 'pear', isOptional: false },
                { name: 'Grated carrot', amount: '1/2 cup', substitute: 'zucchini', isOptional: false },
                { name: 'Oat flour', amount: '1 cup', substitute: 'wheat flour', isOptional: false },
            ],
            steps: [
                { stepNumber: 1, description: 'Preheat oven to 350°F (175°C).' },
                { stepNumber: 2, description: 'Mix wet and dry ingredients together.' },
                { stepNumber: 3, description: 'Pour into a mini muffin tin and bake for 20 mins.' },
            ],
        }
    ];

    for (const recipe of recipesData) {
        await prisma.recipe.create({
            data: {
                title: recipe.title,
                imageUrl: recipe.imageUrl,
                recipeMealType: recipe.recipeMealType,
                minAgeMonths: recipe.minAgeMonths,
                maxAgeMonths: recipe.maxAgeMonths,
                prepTimeMin: recipe.prepTimeMin,
                cookTimeMin: recipe.cookTimeMin,
                difficulty: recipe.difficulty,
                servings: recipe.servings,
                nutritionalFocus: recipe.nutritionalFocus,
                safetyNotes: recipe.safetyNotes,
                isActive: true,
                ingredients: {
                    create: recipe.ingredients,
                },
                steps: {
                    create: recipe.steps,
                },
            },
        });
    }

    console.log(`Seeded ${recipesData.length} recipes.`);
}
